# Generated by Django 6.0.5 on 2026-05-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(blank=True, help_text='可留空由AI生成', max_length=300, verbose_name='摘要'),
        ),
    ]
