upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name localhost;   # 替换为你的域名或 IP,如果只在本地开发/测试（Docker 本地运行），使用 localhost 或直接留空（默认匹配所有请求）

    client_max_body_size 100M;

    location /static/ {
        alias /static/;
    }

    location /media/ {
        alias /media/;
    }

    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}